{% set version = "0.1-10" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-jpeg
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/jpeg_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/jpeg/jpeg_{{ version }}.tar.gz
  sha256: c8d9f609c3088f91ec4853d6cc0e66511038a465811dea79ca6a0c09519178ca

build:
  merge_build_host: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}gzip              # [win]
    - {{ posix }}tar               # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('jpeg')"           # [not win]
    - "\"%R%\" -e \"library('jpeg')\""  # [win]

about:
  home: http://www.rforge.net/jpeg/
  license: GPL-2.0-or-later
  summary: This package provides an easy and simple way to read, write and display bitmap images stored in the JPEG format. It can read and write both files and in-memory raw vectors.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: jpeg
# Version: 0.1-8.1
# Title: Read and write JPEG images
# Author: Simon Urbanek <Simon.Urbanek@r-project.org>
# Maintainer: Simon Urbanek <Simon.Urbanek@r-project.org>
# Depends: R (>= 2.9.0)
# Description: This package provides an easy and simple way to read, write and display bitmap images stored in the JPEG format. It can read and write both files and in-memory raw vectors.
# License: GPL-2 | GPL-3
# SystemRequirements: libjpeg
# URL: http://www.rforge.net/jpeg/
# Packaged: 2019-10-24 14:50:27 UTC; hornik
# NeedsCompilation: yes
# Repository: CRAN
# Date/Publication: 2019-10-24 14:51:52 UTC
