{% set version = '0.1-8' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-jpeg
  version: {{ version|replace("-", "_") }}

source:
  fn: jpeg_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/jpeg_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/jpeg/jpeg_{{ version }}.tar.gz
  sha256: d032befeb3a414cefdbf70ba29a6c01541c54387cc0a1a98a4022d86cbe60a16

build:
  merge_build_host: True  # [win]
  number: 1003
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
  run:
    - r-base
    - {{native}}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('jpeg')"           # [not win]
    - "\"%R%\" -e \"library('jpeg')\""  # [win]

about:
  home: http://www.rforge.net/jpeg/
  license: GPL-2 | GPL-3
  summary: This package provides an easy and simple way to read, write and display bitmap images
    stored in the JPEG format. It can read and write both files and in-memory raw vectors.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
